/**
 * Spotify API service
 * Handles OAuth, track fetching, audio features, and playlist creation
 */

const SPOTIFY_BASE = "https://api.spotify.com/v1";
const SPOTIFY_ACCOUNTS = "https://accounts.spotify.com";

export interface SpotifyTrack {
  id: string;
  name: string;
  artists: { id: string; name: string }[];
  album: { name: string; images: { url: string }[] };
  preview_url: string | null;
  duration_ms: number;
  uri: string;
}

export interface AudioFeatures {
  id: string;
  valence: number;
  energy: number;
  danceability: number;
  tempo: number;
  acousticness: number;
  instrumentalness: number;
}

export interface MoodProfile {
  valence: number;
  energy: number;
  danceability: number;
  tempo: number;
  acousticness?: number;
  instrumentalness?: number;
}

/**
 * Fetch user's top tracks from Spotify
 */
export async function getTopTracks(
  accessToken: string,
  limit = 50,
  timeRange: "short_term" | "medium_term" | "long_term" = "medium_term"
): Promise<SpotifyTrack[]> {
  const res = await fetch(
    `${SPOTIFY_BASE}/me/top/tracks?limit=${limit}&time_range=${timeRange}`,
    {
      headers: { Authorization: `Bearer ${accessToken}` },
    }
  );
  if (!res.ok) throw new Error(`Spotify API error: ${res.status}`);
  const data = await res.json();
  return data.items ?? [];
}

/**
 * Get audio features for a batch of track IDs (max 100)
 */
export async function getAudioFeatures(
  accessToken: string,
  trackIds: string[]
): Promise<AudioFeatures[]> {
  if (trackIds.length === 0) return [];
  const ids = trackIds.slice(0, 100).join(",");
  const res = await fetch(
    `${SPOTIFY_BASE}/audio-features?ids=${encodeURIComponent(ids)}`,
    { headers: { Authorization: `Bearer ${accessToken}` } }
  );
  if (!res.ok) throw new Error(`Spotify API error: ${res.status}`);
  const data = await res.json();
  return (data.audio_features ?? []).filter(Boolean);
}

/**
 * Search for tracks by query
 */
export async function searchTracks(
  accessToken: string,
  query: string,
  limit = 20
): Promise<SpotifyTrack[]> {
  const res = await fetch(
    `${SPOTIFY_BASE}/search?type=track&q=${encodeURIComponent(query)}&limit=${limit}`,
    { headers: { Authorization: `Bearer ${accessToken}` } }
  );
  if (!res.ok) throw new Error(`Spotify API error: ${res.status}`);
  const data = await res.json();
  return data.tracks?.items ?? [];
}

/**
 * Get recommendations based on seed tracks and optional audio feature targets
 */
export async function getRecommendations(
  accessToken: string,
  seedTrackIds: string[],
  targetFeatures?: Partial<MoodProfile>,
  limit = 20
): Promise<SpotifyTrack[]> {
  const params = new URLSearchParams();
  params.set("seed_tracks", seedTrackIds.slice(0, 5).join(","));
  params.set("limit", String(limit));
  if (targetFeatures) {
    Object.entries(targetFeatures).forEach(([k, v]) => {
      if (v != null && typeof v === "number") params.set(`target_${k}`, String(v));
    });
  }
  const res = await fetch(
    `${SPOTIFY_BASE}/recommendations?${params.toString()}`,
    { headers: { Authorization: `Bearer ${accessToken}` } }
  );
  if (!res.ok) throw new Error(`Spotify API error: ${res.status}`);
  const data = await res.json();
  return data.tracks ?? [];
}

/**
 * Create a playlist and add tracks
 */
export async function createPlaylistAndAddTracks(
  accessToken: string,
  userId: string,
  name: string,
  trackUris: string[],
  description?: string
): Promise<{ playlistId: string; snapshotId: string }> {
  const createRes = await fetch(`${SPOTIFY_BASE}/users/${userId}/playlists`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      name,
      description: description ?? `Generated by Tempr`,
      public: false,
    }),
  });
  if (!createRes.ok) throw new Error(`Spotify API error: ${createRes.status}`);
  const playlist = await createRes.json();
  const playlistId = playlist.id;

  // Add tracks in batches of 100
  for (let i = 0; i < trackUris.length; i += 100) {
    const batch = trackUris.slice(i, i + 100);
    const addRes = await fetch(
      `${SPOTIFY_BASE}/playlists/${playlistId}/tracks`,
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${accessToken}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ uris: batch }),
      }
    );
    if (!addRes.ok) throw new Error(`Spotify API error: ${addRes.status}`);
  }

  return { playlistId, snapshotId: playlist.snapshot_id };
}

/**
 * Add track to user's Liked Songs
 */
export async function addToLikedSongs(
  accessToken: string,
  trackIds: string[]
): Promise<void> {
  const res = await fetch(`${SPOTIFY_BASE}/me/tracks`, {
    method: "PUT",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ ids: trackIds }),
  });
  if (!res.ok) throw new Error(`Spotify API error: ${res.status}`);
}

/**
 * Get current user's profile (for userId)
 */
export async function getCurrentUser(
  accessToken: string
): Promise<{ id: string; display_name: string }> {
  const res = await fetch(`${SPOTIFY_BASE}/me`, {
    headers: { Authorization: `Bearer ${accessToken}` },
  });
  if (!res.ok) throw new Error(`Spotify API error: ${res.status}`);
  return res.json();
}
